# Generated by Django 6.1.1 on 2026-10-03 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("programs", "0006_alignmentlink_version_lock"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BinaryField()),
                ("state_hash", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("materialized_at", models.DateTimeField(blank=True, null=True)),
                ("issues", models.JSONField(blank=True, default=list)),
                ("last_error", models.TextField(blank=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s",
                        to="accounts.organization",
                    ),
                ),
                (
                    "version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_document",
                        to="programs.programversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
