# Generated by Django 6.1.1 on 2026-10-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collab", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftdocument",
            name="last_error_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="draftdocument",
            name="saved_seq",
            field=models.BigIntegerField(default=0),
        ),
    ]
