# Generated by Django 6.1.1 on 2026-10-03 10:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("competencies", "0003_competencyimport"),
        ("programs", "0007_alignmentlink_link_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "running"),
                            ("complete", "complete"),
                            ("partial_rules_only", "partial_rules_only"),
                            ("failed", "failed"),
                        ],
                        default="running",
                        max_length=30,
                    ),
                ),
                (
                    "last_run",
                    models.CharField(
                        choices=[("light", "light"), ("full", "full")],
                        default="light",
                        max_length=10,
                    ),
                ),
                ("run_id", models.UUIDField(default=uuid.uuid4)),
                ("rules_version", models.CharField(blank=True, max_length=100)),
                ("ai_prompts", models.JSONField(blank=True, default=dict)),
                ("ai_models", models.JSONField(blank=True, default=dict)),
                ("counts", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s",
                        to="accounts.organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_report",
                        to="programs.programversion",
                    ),
                ),
            ],
            options={
                "ordering": ["version"],
            },
        ),
        migrations.CreateModel(
            name="ObjectiveAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_key", models.UUIDField()),
                ("node_key", models.UUIDField()),
                ("content_hash", models.CharField(max_length=64)),
                ("text", models.TextField(blank=True)),
                ("verb", models.CharField(blank=True, max_length=100)),
                ("level_id", models.PositiveSmallIntegerField(default=0)),
                ("level", models.CharField(blank=True, max_length=50)),
                ("domain", models.CharField(blank=True, max_length=20)),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "high"),
                            ("medium", "medium"),
                            ("low", "low"),
                        ],
                        max_length=10,
                    ),
                ),
                ("components", models.JSONField(default=dict)),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
                ("dimension", models.JSONField(blank=True, null=True)),
                ("ai_status", models.CharField(default="none", max_length=20)),
                (
                    "ai_level_id",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("ai_domain", models.CharField(blank=True, max_length=20)),
                (
                    "ai_confidence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "high"),
                            ("medium", "medium"),
                            ("low", "low"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ai_explanation", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s",
                        to="accounts.organization",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectives",
                        to="quality.qualityreport",
                    ),
                ),
            ],
            options={
                "ordering": ["report", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("report", "block_key"), name="quality_objective_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("kind", models.CharField(max_length=60)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "critical"),
                            ("warning", "warning"),
                            ("info", "info"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("rule", "rule"), ("ai", "ai")],
                        default="rule",
                        max_length=10,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "high"),
                            ("medium", "medium"),
                            ("low", "low"),
                        ],
                        max_length=10,
                    ),
                ),
                ("node_key", models.UUIDField(blank=True, null=True)),
                ("block_key", models.UUIDField(blank=True, null=True)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("explanation", models.TextField(blank=True)),
                ("dismissed_reason", models.TextField(blank=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "competency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="competencies.competency",
                    ),
                ),
                (
                    "dismissed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s",
                        to="accounts.organization",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="quality.qualityreport",
                    ),
                ),
            ],
            options={
                "ordering": ["report", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("report", "source", "fingerprint"),
                        name="quality_finding_unique",
                    )
                ],
            },
        ),
    ]
