# Generated by Django 6.1.1 on 2026-10-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectiveanalysis",
            name="ai_content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="objectiveanalysis",
            name="ai_level",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="objectiveanalysis",
            name="ai_model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="objectiveanalysis",
            name="ai_verb",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="qualityreport",
            name="ai_state",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
