# Generated by Django 6.1.1 on 2026-10-03 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("quality", "0002_objectiveanalysis_ai_content_hash_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AICheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("link", "link"), ("suggestion", "suggestion")],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("basis_hash", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=20)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("model", models.CharField(blank=True, max_length=100)),
                (
                    "organization",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s",
                        to="accounts.organization",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="quality.qualityreport",
                    ),
                ),
            ],
            options={
                "ordering": ["report", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("report", "kind", "subject"),
                        name="quality_check_unique",
                    )
                ],
            },
        ),
    ]
