# Generated by Django 6.1.1 on 2026-10-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0003_aicheck"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualityreport",
            name="inherited",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
