# Generated by Django 6.1.1 on 2026-10-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="kind",
            field=models.CharField(
                choices=[("upload", "upload"), ("export", "export"), ("logo", "logo")],
                max_length=10,
            ),
        ),
    ]
