# Generated by Django 6.1.1 on 2026-10-06 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_organization_logo_file"),
        ("programs", "0007_alignmentlink_link_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files",
                to="programs.programversion",
            ),
        ),
    ]
