# Generated by Django 6.1.1 on 2026-10-05 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0002_reminder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowinstance",
            name="previous",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="next",
                to="workflows.workflowinstance",
            ),
        ),
    ]
