# Generated by Django 6.1.1 on 2026-10-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event",
            field=models.CharField(
                choices=[
                    ("task_assigned", "task_assigned"),
                    ("version_returned", "version_returned"),
                    ("version_approved", "version_approved"),
                    ("task_due_soon", "task_due_soon"),
                    ("task_due", "task_due"),
                    ("task_overdue", "task_overdue"),
                    ("export_failed", "export_failed"),
                ],
                max_length=30,
            ),
        ),
    ]
