# Generated by Django 6.1.1 on 2026-10-02 23:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("programs", "0002_target_version_lock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("level", models.PositiveSmallIntegerField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=500)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s",
                        to="accounts.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="programs.node",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="programs.programversion",
                    ),
                ),
            ],
            options={
                "ordering": ["version", "level", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("objective", "objective"),
                            ("content", "content"),
                            ("activity", "activity"),
                            ("assessment", "assessment"),
                            ("reference", "reference"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.JSONField()),
                ("content_hash", models.CharField(max_length=64)),
                ("order", models.PositiveIntegerField(default=0)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s",
                        to="accounts.organization",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="programs.programversion",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blocks",
                        to="programs.node",
                    ),
                ),
            ],
            options={
                "ordering": ["version", "node", "order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.UniqueConstraint(
                fields=("version", "node_key"), name="programs_node_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="block",
            constraint=models.UniqueConstraint(
                fields=("version", "block_key"), name="programs_block_key_unique"
            ),
        ),
    ]
