# Generated by Django 6.1.1 on 2026-10-02 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("competencies", "0003_competencyimport"),
        ("programs", "0004_node_block_version_lock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlignmentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("objective_competency", "objective_competency"),
                            ("assessment_objective", "assessment_objective"),
                            ("objective_parent", "objective_parent"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s",
                        to="accounts.organization",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_links",
                        to="programs.block",
                    ),
                ),
                (
                    "target_block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_links",
                        to="programs.block",
                    ),
                ),
                (
                    "target_competency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="competencies.competency",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alignment_links",
                        to="programs.programversion",
                    ),
                ),
            ],
            options={
                "ordering": ["version", "kind", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("kind", "objective_competency"),
                                ("target_block__isnull", True),
                                ("target_competency__isnull", False),
                            ),
                            models.Q(
                                models.Q(
                                    ("kind", "objective_competency"), _negated=True
                                ),
                                ("target_block__isnull", False),
                                ("target_competency__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="programs_link_target_matches_kind",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("target_competency__isnull", False)),
                        fields=("version", "kind", "source", "target_competency"),
                        name="programs_link_competency_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("target_block__isnull", False)),
                        fields=("version", "kind", "source", "target_block"),
                        name="programs_link_block_unique",
                    ),
                ],
            },
        ),
    ]
