# Generated by Django 6.1.1 on 2026-10-03 00:01

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("competencies", "0003_competencyimport"),
        ("programs", "0006_alignmentlink_version_lock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alignmentlink",
            name="link_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddConstraint(
            model_name="alignmentlink",
            constraint=models.UniqueConstraint(
                fields=("version", "link_key"), name="programs_link_key_unique"
            ),
        ),
    ]
