# Generated by Django 6.1.1 on 2026-10-03 00:01; the backfill was added after review: a column added with a
# callable default gets one value for every existing row, which broke the unique constraint on real data.

import uuid

from django.conf import settings
from django.db import migrations, models

# Rows of locked versions may not be updated (the version lock trigger, D20); giving them a key is not a content
# change, so the trigger is set aside for this one statement inside the migration's transaction.
BACKFILL = """
ALTER TABLE programs_alignmentlink DISABLE TRIGGER programs_alignmentlink_version_lock;
UPDATE programs_alignmentlink SET link_key = gen_random_uuid() WHERE link_key IS NULL;
ALTER TABLE programs_alignmentlink ENABLE TRIGGER programs_alignmentlink_version_lock;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("competencies", "0003_competencyimport"),
        ("programs", "0006_alignmentlink_version_lock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alignmentlink",
            name="link_key",
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunSQL(BACKFILL, reverse_sql=migrations.RunSQL.noop),
        migrations.AlterField(
            model_name="alignmentlink",
            name="link_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddConstraint(
            model_name="alignmentlink",
            constraint=models.UniqueConstraint(fields=("version", "link_key"), name="programs_link_key_unique"),
        ),
    ]
