# Generated by Django 6.1.1 on 2026-10-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sso", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="identityproviderconfig",
            name="last_test_error_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="verifieddomain",
            name="last_error_code",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
