# Generated by Django 6.1.1 on 2026-10-05 09:22

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="work_days",
            field=models.JSONField(
                default=apps.accounts.models.default_work_days,
                validators=[apps.accounts.models.validate_work_days],
            ),
        ),
    ]
