# Generated by Django 6.1.1 on 2026-10-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_totp_and_mfa_requirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="totpdevice",
            name="failures",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="totpdevice",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
