# Generated by Django 6.1.1 on 2026-10-06 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_totp_failure_lock"),
        ("files", "0002_organization_logo_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="logo",
        ),
        migrations.AddField(
            model_name="organization",
            name="logo_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="files.file",
            ),
        ),
    ]
