# Generated by Django 6.1.1 on 2026-10-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestion",
            name="kind",
            field=models.CharField(
                choices=[
                    ("rewrite", "rewrite"),
                    ("outline", "outline"),
                    ("import", "import"),
                ],
                max_length=20,
            ),
        ),
    ]
